# Copyright 2024 The Forgejo Authors
# SPDX-License-Identifier: MIT
#
name: issue-labels

on:
  pull_request_target:
    types:
      - labeled

jobs:
  end-to-end:
    if: >
      vars.ROLE == 'forgejo-coding' &&

      secrets.END_TO_END_CASCADING_PR_DESTINATION != '' &&
      secrets.END_TO_END_CASCADING_PR_ORIGIN != '' &&

      (
        github.event_name == 'push' ||
        (
          github.event_name == 'pull_request_target' &&
          github.event.action == 'label_updated' &&
          github.event.label.name == 'run-end-to-end-tests'
        )
      )
    runs-on: docker
    container:
      image: code.forgejo.org/oci/node:20-bookworm
    steps:
      - name: Debug info
        run: |
          cat <<'EOF'
          ${{ toJSON(github) }}
          EOF
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
          show-progress: 'false'
      - uses: actions/cascading-pr@v2
        with:
          origin-url: ${{ env.GITHUB_SERVER_URL }}
          origin-repo: ${{ github.repository }}
          origin-token: ${{ secrets.END_TO_END_CASCADING_PR_ORIGIN }}
          origin-pr: ${{ github.event.pull_request.number }}
          origin-ref: ${{ github.event_name == 'push' && github.event.ref || '' }}
          destination-url: https://code.forgejo.org
          destination-fork-repo: cascading-pr/end-to-end
          destination-repo: forgejo/end-to-end
          destination-branch: main
          destination-token: ${{ secrets.END_TO_END_CASCADING_PR_DESTINATION }}
          close-merge: true
          update: .forgejo/cascading-pr-end-to-end
