# Copyright 2024 The Forgejo Authors
# SPDX-License-Identifier: MIT
#
name: milestone

on:
  pull_request_target:
    types:
      - closed

jobs:
  set:
    if: vars.ROLE == 'forgejo-coding' && github.event.pull_request.merged
    runs-on: docker
    container:
      image: 'data.forgejo.org/oci/ci:1'
    steps:
      - uses: https://data.forgejo.org/forgejo/set-milestone@v1.0.0
        with:
          forgejo: https://codeberg.org
          repository: forgejo/forgejo
          token: ${{ secrets.SET_MILESTONE_TOKEN }}
          pr-number: ${{ github.event.pull_request.number }}
          verbose: ${{ vars.SET_MILESTONE_VERBOSE }}
