# Copyright 2024 The Forgejo Authors
# SPDX-License-Identifier: MIT
#
# This workflow is triggered on pull_request_target and runs from
# the forgejo branch so that it does not need to be backported.
# If it was triggered on pull_request, it would have to exist on all
# stable branches.
#
name: milestone

on:
  pull_request_target:
    types:
      - opened

jobs:
  set:
    if: vars.ROLE == 'forgejo-coding'
    runs-on: docker
    container:
      image: 'code.forgejo.org/oci/ci:1'
    steps:
      - uses: https://code.forgejo.org/forgejo/set-milestone@v1.0.0
        with:
          forgejo: https://codeberg.org
          repository: forgejo/forgejo
          token: ${{ secrets.SET_MILESTONE_TOKEN }}
          pr-number: ${{ github.event.pull_request.number }}
          verbose: ${{ vars.SET_MILESTONE_VERBOSE }}
