name: issue-labels

on:
  pull_request_target:
    types:
      - edited
      - synchronize
      - labeled

jobs:
  release-notes:
    if: >
      vars.ROLE == 'forgejo-coding' &&

      secrets.RELEASE_NOTES_ASSISTANT_TOKEN != '' &&

      github.event_name == 'pull_request' &&
      contains(github.event.pull_request.labels.*.name, 'worth a release-note') &&
      (
        github.event.action == 'label_updated' ||
        github.event.action == 'edited' ||
        github.event.action == 'synchronized'
      )

    runs-on: docker
    container:
      image: 'code.forgejo.org/oci/node:20-bookworm'
    steps:
      - name: Debug info
        run: |
          cat <<'EOF'
          ${{ toJSON(github) }}
          EOF

      - uses: https://code.forgejo.org/actions/checkout@v4

      - uses: https://code.forgejo.org/actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache: false

      - name: apt install jq
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt-get update -qq
          apt-get -q install -y -qq jq

      - name: release-notes-assistant preview
        run: |
          go run code.forgejo.org/forgejo/release-notes-assistant@v1.1.1 --config .release-notes-assistant.yaml --storage pr --storage-location ${{ github.event.pull_request.number }}  --forgejo-url $GITHUB_SERVER_URL --repository $GITHUB_REPOSITORY --token ${{ secrets.RELEASE_NOTES_ASSISTANT_TOKEN }} preview ${{ github.event.pull_request.number }}
